### ISSUE TITLE
interface conversion: interface {} is nil, not float64

### ISSUE THREAD

**Issue by tomczyn** [westerlind/alfred-raindrop-search#32]
I've installed and authenticated to the extension successfully, but every time I want to search for something, I get an error:

```
interface conversion: interface {} is nil, not float64
```

<img width="713" alt="Zrzut ekranu 2024-08-7 o 11 27 50" src="https://github.com/user-attachments/assets/247be53a-6566-46f1-beef-11521d5a6495">

**Comment by westerlind** [comment]
Hi @tomczyn 

could you open the Alfred settings, go to the Raindrop workflow, and enable the debugging mode (top right corner) and check the log from the debug console when you try to search again.

If you could post that log here, I might be able to figure out what is causing this.

**Comment by tomczyn** [comment]
Hi, of course, here's the output:

```
[12:18:24.825] Logging Started...
[12:18:29.484] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[12:18:29.845] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[12:18:29.853] STDERR: Search Raindrop.io[Script Filter] 🍺
12:18:29 workflow.go:328: ---- Search Raindrop.io/2.0.11 (AwGo/0.27.1) -----
12:18:29 feedback.go:509: Sent 2 result(s) to Alfred
12:18:29 workflow.go:405: ------------------ 315.454125ms ------------------
[12:18:29.857] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "123456"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[12:18:30.523] Search Raindrop.io[Script Filter] Queuing argument 'tes'
[12:18:30.865] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[12:18:30.872] ERROR: Search Raindrop.io[Script Filter] Code 1: 🍺
12:18:30 workflow.go:328: ---- Search Raindrop.io/2.0.11 (AwGo/0.27.1) -----
12:18:30 workflow.go:343: ------------------ FATAL ERROR -------------------
12:18:30 workflow.go:344: interface conversion: interface {} is nil, not float64 : goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/deanishe/awgo.(*Workflow).Run.func2()
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:344 +0xf4
panic({0x102fd5dc0?, 0x140002e3410?})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:914 +0x218
main.render_collections({0x140002f8000?, 0x0?, 0xc}, {0x140002bc380, 0x8, 0x8}, {0x102f0836f, 0x5}, {0x102f0b5bc, 0x9}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12346/raindrop_common.go:354 +0x1d98
main.render_collections({0x140002f8000?, 0x6?, 0xc}, {0x140002bc380, 0x8, 0x8}, {0x102f0836f, 0x5}, {0x102f0b5bc, 0x9}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-123456/raindrop_common.go:451 +0x1050
main.search({0x102f0ab58?, 0x103255b40?}, {0x16d1738b9, 0x3}, {0x0?, 0x102f159be?}, {0x0, 0x0}, {0x0?, 0x140000122a0?}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-123456/raindrop_search.go:113 +0x1578
main.run()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_main.go:52 +0x6a0
github.com/deanishe/awgo.(*Workflow).Run(0x140000005a0, 0x103028bc8)
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:358 +0x2bc
main.main()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345366/raindrop_main.go:86 +0x1f0
12:18:30 workflow.go:345: ---------------- END STACK TRACE -----------------
12:18:30 feedback.go:509: Sent 1 result(s) to Alfred
12:18:30 workflow.go:376: [ERROR] interface conversion: interface {} is nil, not float64
12:18:30 workflow.go:402: ------------------ 287.398875ms ------------------
[12:18:30.875] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "1234567"
  },
  "items": [
    {
      "title": "interface conversion: interface {} is nil, not float64",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
[12:18:30.905] Search Raindrop.io[Script Filter] Queuing argument 'test'
[12:18:31.294] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[12:18:31.305] ERROR: Search Raindrop.io[Script Filter] Code 1: 🍺
12:18:30 workflow.go:328: ---- Search Raindrop.io/2.0.11 (AwGo/0.27.1) -----
12:18:31 workflow.go:343: ------------------ FATAL ERROR -------------------
12:18:31 workflow.go:344: interface conversion: interface {} is nil, not float64 : goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/deanishe/awgo.(*Workflow).Run.func2()
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:344 +0xf4
panic({0x104ccddc0?, 0x14000321050?})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:914 +0x218
main.render_collections({0x1400032c000?, 0x0?, 0xc}, {0x14000146700, 0x8, 0x8}, {0x104c0036f, 0x5}, {0x104c035bc, 0x9}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-61AD0823A468/raindrop_common.go:354 +0x1d98
main.render_collections({0x1400032c000?, 0x6?, 0xc}, {0x14000146700, 0x8, 0x8}, {0x104c0036f, 0x5}, {0x104c035bc, 0x9}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-61AD0823A468/raindrop_common.go:451 +0x1050
main.search({0x104c02b58?, 0x104f4db40?}, {0x16b47b8b9, 0x4}, {0x0?, 0x104c0d9be?}, {0x0, 0x0}, {0x0?, 0x140000122a0?}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-61AD0823A468/raindrop_search.go:113 +0x1578
main.run()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-61AD0823A468/raindrop_main.go:52 +0x6a0
github.com/deanishe/awgo.(*Workflow).Run(0x140000005a0, 0x104d20bc8)
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:358 +0x2bc
main.main()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-6GFDREA468/raindrop_main.go:86 +0x1f0
12:18:31 workflow.go:345: ---------------- END STACK TRACE -----------------
12:18:31 feedback.go:509: Sent 1 result(s) to Alfred
12:18:31 workflow.go:376: [ERROR] interface conversion: interface {} is nil, not float64
12:18:31 workflow.go:402: ------------------ 348.391208ms ------------------
[12:18:31.307] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "1234567"
  },
  "items": [
    {
      "title": "interface conversion: interface {} is nil, not float64",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by westerlind** [comment]
@tomczyn could you test if the attached version of the workflow fixes your issue?

[Search Raindrop.io-test.zip](https://github.com/user-attachments/files/16532005/Search.Raindrop.io-test.zip)

**Comment by tomczyn** [comment]
@westerlind thank you for a speedy response. Unfortunately the error persists

```
[19:20:01.283] Logging Started...
[19:20:03.456] Search Raindrop.io[Script Filter] Queuing argument '(null)'
[19:20:03.859] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[19:20:03.863] STDERR: Search Raindrop.io[Script Filter] 🍺
19:20:03 workflow.go:328: --- Search Raindrop.io/2.0.11.5 (AwGo/0.27.1) ----
19:20:03 feedback.go:509: Sent 2 result(s) to Alfred
19:20:03 workflow.go:405: ------------------ 24.275917ms -------------------
[19:20:03.866] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "123456"
  },
  "items": [
    {
      "title": "Search your Raindrop.io bookmarks",
      "subtitle": "Or press enter to open Raindrop.io",
      "arg": "https://app.raindrop.io/",
      "valid": true,
      "variables": {
        "goto": "open"
      },
      "mods": {
        "alt": {
          "arg": "https://app.raindrop.io/",
          "subtitle": "Or press enter to open Raindrop.io",
          "variables": {
            "goto": "open"
          }
        }
      }
    },
    {
      "title": "Browse your Raindrop.io collections",
      "subtitle": "",
      "valid": true,
      "icon": {
        "path": "folder.png"
      },
      "variables": {
        "goto": "browse"
      },
      "mods": {
        "alt": {
          "subtitle": "",
          "variables": {
            "goto": "browse"
          }
        }
      }
    }
  ]
}
[19:20:04.126] Search Raindrop.io[Script Filter] Queuing argument 'test'
[19:20:04.368] Search Raindrop.io[Script Filter] Script with argv '(null)' finished
[19:20:04.379] ERROR: Search Raindrop.io[Script Filter] Code 1: 🍺
19:20:04 workflow.go:328: --- Search Raindrop.io/2.0.11.5 (AwGo/0.27.1) ----
19:20:04 workflow.go:343: ------------------ FATAL ERROR -------------------
19:20:04 workflow.go:344: interface conversion: interface {} is nil, not float64 : goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/deanishe/awgo.(*Workflow).Run.func2()
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:344 +0xf4
panic({0x103107920?, 0x14000266480?})
	/opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/panic.go:770 +0x124
main.collection_paths({0x14000256000?, 0x14000227b90?, 0xc}, {0x14000222280, 0x8, 0x8}, 0x4?, 0x296983e, {0x140002011a0?, 0x4?, ...}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_common.go:322 +0x408
main.collection_paths({0x14000256000?, 0x24?, 0xc}, {0x14000222280, 0x8, 0x8}, 0x140000ae0d8?, 0x0, {0x0?, 0x1274ff?, ...}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_common.go:327 +0x3a0
main.search({0x103035a81?, 0x1033d1ca0?}, {0x16d0638b9, 0x4}, {0x0?, 0x103040c53?}, {0x0, 0x0}, {0x0?, 0x140000be360?}, ...)
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_search.go:177 +0x1334
main.run()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_main.go:52 +0x6a0
github.com/deanishe/awgo.(*Workflow).Run(0x140000ea5a0, 0x10315bca8)
	/Users/andreas/go/pkg/mod/github.com/deanishe/awgo@v0.29.0/workflow.go:358 +0x2bc
main.main()
	/Users/andreas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1B8F238D-BB91-410E-8CE1-12345/raindrop_main.go:86 +0x1f0
19:20:04 workflow.go:345: ---------------- END STACK TRACE -----------------
19:20:04 feedback.go:509: Sent 1 result(s) to Alfred
19:20:04 workflow.go:376: [ERROR] interface conversion: interface {} is nil, not float64
19:20:04 workflow.go:402: ------------------ 207.255916ms ------------------
[19:20:04.382] Search Raindrop.io[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "123456"
  },
  "items": [
    {
      "title": "interface conversion: interface {} is nil, not float64",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by westerlind** [comment]
@tomczyn a little tricky without being able to reproduce the problem myself, but let's try again. Check if this version works better.

[Search Raindrop.io-test2.zip](https://github.com/user-attachments/files/16532176/Search.Raindrop.io-test2.zip)

**Comment by tomczyn** [comment]
@westerlind this one works, thank you so much ❤️

**Comment by westerlind** [comment]
That's great!
A new official version will be out soon with this fix included.
